# CAMERA BOARD v1

# pmoda[0]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[0]" ]
# pmoda[1]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[1]" ]
# pmoda[2]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[2]" ]
# pmoda[3]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[3]" ]
# pmoda[4]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[4]" ]
# pmoda[5]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[5]" ]
# pmoda[6]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[6]" ]
# pmoda[7]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33}  [ get_ports "camera_d[7]" ]

# pmodb[3]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33 DRIVE 24} [get_ports "cam_xclk" ]
# pmodb[2]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports "cam_hsync" ]
# pmodb[5]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports "i2c_sda" ]
# pmodb[0]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports "cam_pclk" ]
# pmodb[1]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports "cam_vsync" ]
# pmodb[6]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33 PULLTYPE PULLUP} [get_ports "i2c_scl" ]
